$aux_dir = "../../build";
$tmpdir  = "../../build";
$out_dir = "../../build";

ensure_path( 'TEXINPUTS', './/' );
ensure_path( 'TEXINPUTS', '../../themes//' );
ensure_path( 'TEXINPUTS', '../../fonts//' );
